### ISSUE TITLE
add a requiredIf/optionalUnless

### ISSUE THREAD

**Issue by skoop** [particle-php/Validator#85] opened 2015-09-21 13:35 UTC
Sometimes you may have fields that are optional in some situations, but required in other situations. For instance in a form where one should fill in invoice address details with an optional different delivery address. Based on the checkbox 'different delivery address', the delivery address fields are either required or optional.

The situation I'm running into right now is that I mark the fields as optional. Because of this, the validations after optional() are not run when the field is empty. This is correct behaviour when people don't check the 'different delivery address' checkbox, but when they *do* check the checkbox, it still won't run the validations.

I propose a requiredIf or optionalUnless that would contain a callable and would receive all fields and would mark the field as required if the callable returns true or optional if the callback returns falls.

**Comment by RickvdStaaij** [comment] 2015-09-21 15:13
In fact, that's already possible:

```php
$this->validator
    ->optional('deliveryAddress')->required(function ($values) {
        return (isset($values['differentDelivery']) && $values['differentDelivery'] === true);
    });
```

We should add that to the documentation :wink:

**Comment by skoop** [comment] 2015-09-21 15:14
oh, I love you guys. you already implemented the stuff I need! But yeah, having it in the documentation would be awesome :)

**Comment by skoop** [comment] 2015-09-22 07:54
@RickvdStaaij hmm... either I'm doing something weird, or this doesn't actually work. I have the following code:

```php
        $this->validator->optional('client_shipping_name')->required(function ($values) {
            if (
                isset($values['different_shipping_address']) &&
                $values['different_shipping_address'] == "1"
            ) {
                return true;
            }
            return false;
        })->lengthBetween(2, null)->callback(function($value) {
            if (empty(trim($value))) {
                throw new InvalidValueException(
                    'Validation.NotEmptyWhenDifferentShippingAddress',
                    'client_shipping_address'
                );
            }

            return true;
        });
```

through good old var_dump/die debugging I've found out the required() function is returning true, yet the validations are not executed. Am I missing something?

**Comment by berry-langerak** [comment] 2015-09-22 13:24
@skoop You old bug finder. Can you build a reproduction thingy? As in, what data are you validating?

**Comment by skoop** [comment] 2015-09-22 14:37
@berry-langerak *evilgrin*

I'll have to build a fictional example, something about security and iso certifications and such. give me a minute.

**Comment by berry-langerak** [comment] 2015-09-22 14:41
Sure, thanks, would be nice. Can't reproduce it here, but there is one small weird thingy:

```php
$v = new Validator;
$v->optional('foo')->lengthBetween(1, 2)->required(function ($values) {
   return array_key_exists('bar', $values);
});
$v->validate(['bar' => true, 'foo' => '']); // bool(true)
```

This is due to the fact that allowEmpty is true by default for optional rules, but maybe this is not the issue you're running into.

**Comment by skoop** [comment] 2015-09-22 15:01
it's going to be tomorrow, it is, gotta go now :)

**Comment by berry-langerak** [comment] 2015-10-30 10:18
@skoop any chance you could get me a reproduction scenario, so we can test and fix this?

**Comment by RickvdStaaij** [comment] 2016-08-05 09:50
I'm going to close this to make a more concrete issue: https://github.com/particle-php/Validator/issues/142. @skoop if you run into the issue again, please let us know the details :)

**Closed by RickvdStaaij** 2016-08-05 09:50 UTC
Labels: bug
